{
  "swagger": "2.0",
  "paths": {
    "/manager/users/{id}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Specific User",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/ShowUserResponse"
            },
            "description": "User created OK"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "The id of the user"
          }
        ],
        "operationId": "HangmanWeb.UserController.get_user",
        "description": "Return JSON with an especific user",
        "deprecated": false
      },
      "delete": {
        "tags": [
          "User"
        ],
        "summary": "Specific User",
        "responses": {
          "205": {
            "schema": {
              "$ref": "#/definitions/DeleteUserResponse"
            },
            "description": "Deleted"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "The id of the user"
          }
        ],
        "operationId": "HangmanWeb.UserController.delete_user",
        "description": "Return JSON with an especific user",
        "deprecated": false
      }
    },
    "/manager/users/pass/{id}": {
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Update a user",
        "responses": {
          "205": {
            "schema": {
              "$ref": "#/definitions/UpdateUserPasswordResponse"
            },
            "description": "Updated"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "The id of the user"
          },
          {
            "schema": {
              "$ref": "#/definitions/UpdateUserPasswordRequest"
            },
            "required": true,
            "name": "name",
            "in": "body",
            "description": "The user details"
          }
        ],
        "operationId": "HangmanWeb.UserController.update_password",
        "description": "Update the user password",
        "deprecated": false
      }
    },
    "/manager/users/name/{id}": {
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Update a user",
        "responses": {
          "205": {
            "schema": {
              "$ref": "#/definitions/UpdateUserNameResponse"
            },
            "description": "Updated"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "string",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "The id of the user"
          },
          {
            "schema": {
              "$ref": "#/definitions/UpdateUserNameRequest"
            },
            "required": true,
            "name": "name",
            "in": "body",
            "description": "The user details"
          }
        ],
        "operationId": "HangmanWeb.UserController.update_name",
        "description": "Update the user name",
        "deprecated": false
      }
    },
    "/manager/users": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Add a new user",
        "responses": {
          "201": {
            "schema": {
              "$ref": "#/definitions/CreateUserResponse"
            },
            "description": "Created"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "schema": {
              "$ref": "#/definitions/CreateUserRequest"
            },
            "required": true,
            "name": "user",
            "in": "body",
            "description": "The user details"
          }
        ],
        "operationId": "HangmanWeb.UserController.create_user",
        "description": "Create a new user in the database",
        "deprecated": false
      },
      "get": {
        "tags": [
          "User"
        ],
        "summary": "All Users",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/ShowUsersResponse"
            },
            "description": "Success"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "operationId": "HangmanWeb.UserController.get_users",
        "description": "Return JSON with all users listed in the database",
        "deprecated": false
      }
    },
    "/manager/logout": {
      "delete": {
        "tags": [
          "Session"
        ],
        "summary": "Delete session",
        "responses": {
          "205": {
            "description": "Session ended"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "operationId": "HangmanWeb.SessionController.delete_session",
        "description": "Delete the session",
        "deprecated": false
      }
    },
    "/manager/login": {
      "post": {
        "tags": [
          "Session"
        ],
        "summary": "Create session",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/CreateSessionResponse"
            },
            "description": "Success"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "schema": {
              "$ref": "#/definitions/CreateSessionRequest"
            },
            "required": false,
            "name": "user",
            "in": "body",
            "description": "The user details"
          }
        ],
        "operationId": "HangmanWeb.SessionController.create_session",
        "description": "Return the id of the user if it's found and the password is valid and create a session",
        "deprecated": false
      }
    }
  },
  "info": {
    "version": "1.0",
    "title": "Users API"
  },
  "host": "localhost:4000",
  "definitions": {
    "User": {
      "type": "object",
      "title": "User",
      "required": [
        "name"
      ],
      "properties": {
        "updated_at": {
          "type": "string",
          "format": "datetime",
          "description": "Update timestamp"
        },
        "name": {
          "type": "string",
          "description": "User name"
        },
        "inserted_at": {
          "type": "string",
          "format": "datetime",
          "description": "Creation timestamp"
        },
        "id": {
          "type": "integer",
          "description": "User ID"
        },
        "credential": {
          "$ref": "#/definitions/Credential"
        }
      },
      "description": "Managers for the words list"
    },
    "UpdateUserPasswordResponse": {
      "type": "object",
      "title": "ShowUserResponse",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "description": "The user updated"
        }
      },
      "example": {
        "user": {
          "name": "Jose",
          "id": 1,
          "email": "juan@cordage.io",
          "active": true
        }
      },
      "description": "Response schema of a single user"
    },
    "UpdateUserPasswordRequest": {
      "type": "object",
      "title": "ShowUserResponse",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "description": "The user password"
        }
      },
      "example": {
        "password_confirmation": "Qwerty2021",
        "password": "Qwerty2021"
      },
      "description": "Request params to update the password of a user"
    },
    "UpdateUserNameResponse": {
      "type": "object",
      "title": "ShowUserResponse",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "description": "The user updated"
        }
      },
      "example": {
        "user": {
          "name": "Jose",
          "id": 1,
          "email": "juan@cordage.io",
          "active": false
        }
      },
      "description": "Response schema of a single user"
    },
    "UpdateUserNameRequest": {
      "type": "object",
      "title": "ShowUserResponse",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "description": "The user name"
        }
      },
      "example": {
        "name": "Jose"
      },
      "description": "Reques params to update a name of the user"
    },
    "ShowUsersResponse": {
      "type": "object",
      "title": "CreateUserResponse",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "description": "The list of users"
        }
      },
      "example": {
        "user": {
          "name": "Juan",
          "id": 1,
          "email": "juan@cordage.io",
          "active": false
        }
      },
      "description": "Response schema of the user created"
    },
    "ShowUserResponse": {
      "type": "object",
      "title": "ShowUserResponse",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "description": "The user found"
        }
      },
      "example": {
        "user": {
          "name": "Juan",
          "id": 1,
          "email": "juan@cordage.io",
          "active": false
        }
      },
      "description": "Response schema of a single user"
    },
    "ShowUserRequest": {
      "type": "object",
      "title": "ShowUserRequest",
      "description": "Request params to update a user"
    },
    "DeleteUserResponse": {
      "type": "object",
      "title": "DeleteUserResponse",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "description": "The user deleted"
        }
      },
      "example": {
        "user": {
          "name": "Juan",
          "id": 1,
          "email": "juan@cordage.io",
          "active": false
        }
      },
      "description": "Response schema of a single user"
    },
    "DeleteUserRequest": {
      "type": "object",
      "title": "DeleteUserRequest",
      "description": "Request params to delete a user"
    },
    "Credential": {
      "type": "object",
      "title": "Credential",
      "required": [
        "active",
        "admin",
        "email"
      ],
      "properties": {
        "user": {
          "$ref": "#/definitions/User"
        },
        "updated_at": {
          "type": "string",
          "format": "datetime",
          "description": "Update timestamp"
        },
        "password_hash": {
          "type": "string"
        },
        "password_confirmation": {
          "type": "string",
          "description": "Virtual Password Confirmation"
        },
        "password": {
          "type": "string",
          "description": "Virtual Password"
        },
        "inserted_at": {
          "type": "string",
          "format": "datetime",
          "description": "Creation timestamp"
        },
        "id": {
          "type": "integer",
          "description": "Credential ID"
        },
        "email": {
          "type": "string",
          "description": "User Email"
        },
        "admin": {
          "type": "boolean",
          "description": "User is a Super Manenger"
        },
        "active": {
          "type": "boolean",
          "description": "User has verified email"
        }
      },
      "description": "Managers credential"
    },
    "CreateUserResponse": {
      "type": "object",
      "title": "CreateUserResponse",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "description": "The user created"
        }
      },
      "example": {
        "user": {
          "name": "Juan",
          "id": 1,
          "email": "juan@cordage.io",
          "active": false
        }
      },
      "description": "Response schema of the user created"
    },
    "CreateUserRequest": {
      "type": "object",
      "title": "CreateUserRequest",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "description": "The user name and email"
        }
      },
      "example": {
        "name": "Juan",
        "email": "juan@cordage.io"
      },
      "description": "POST body for creating a user"
    },
    "CreateSessionResponse": {
      "type": "object",
      "title": "CreateSessionResponse",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "description": "The users details"
        }
      },
      "example": {
        "user_id": 1,
        "token_refresh": "SFMyNTY.g2gDYQduBgA01y8LfQFiAAFRgA.9mGWauIJ7RdO86yfQ_m9wvXefmb5kEy8yiI57yOOz5o",
        "token_auth": "SFMyNTY.g2gDYQduBgA01y8LfQFiAAFRgA.5IuDTyU07BU1DdTfVLPv5aDydsg7tdRNMhC33cL__NA"
      },
      "description": "Response and id"
    },
    "CreateSessionRequest": {
      "type": "object",
      "title": "CreateUserRequest",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          },
          "description": "The users details"
        }
      },
      "example": {
        "password": "Qwerty2021",
        "email": "juan@cordage.io"
      },
      "description": "POST body for creating a user"
    }
  }
}